import type { Metadata } from 'next';
import { poppins } from '@/app/font';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import './globals.css';
import { Providers } from '@/components/Providers';
import { Toaster } from 'sonner';
import React from 'react';
import DesignerContextProvider from '@/context/DesignerContext';
import NextTopLoader from 'nextjs-toploader';
import UserContextProvider from '@/context/UserContext';

export const metadata: Metadata = {
  title: 'Create custom forms',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} h-full w-full`} suppressHydrationWarning>
      <body className="h-full w-full">
        <NextTopLoader />
        <DesignerContextProvider>
          <UserContextProvider>
            <Providers>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </Providers>
          </UserContextProvider>
        </DesignerContextProvider>
      </body>
    </html>
  );
}
